// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int n = Integer.parseInt(args[0]);
	   int low = 0;
	   int high = 0;
	   for(int i = 0; i<n; i++){
		if (Math.random()<0.5) {
			low++;
		}else {
			high++;
		}
	   }
	   System.out.println("> 0.5: " + high+ " times" );
	   System.out.println("<= 0.5: " + low + " times" );
	}
}
